### ISSUE TITLE
Outdated Woocommerce files

### ISSUE THREAD

**Issue by nodarik** [ColorlibHQ/tyche#52]
tyche/woocommerce/archive-product.php version 3.3.0 is out of date. The core version is 3.4.0, 
tyche/woocommerce/single-product/add-to-cart/external.php version 2.1.0 is out of date. The core version is 3.4.0, 
tyche/woocommerce/single-product/add-to-cart/grouped.php version 3.3.0 is out of date. The core version is 3.4.0, 
tyche/woocommerce/single-product/add-to-cart/simple.php version 3.0.0 is out of date. The core version is 3.4.0, 
tyche/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php version 3.0.0 is out of date. The core

**Comment by puikinsh** [comment]
Lately getting a lot of reports about this. Would be great to fix it sooner than later.

**Comment by cristianraiber** [comment]
@puikinsh - OK, moved to the top of the priority list :)

**Comment by nodarik** [comment]
Hey guys, this is still problem since woocommerce update, so we need to update files again

**Comment by cristianraiber** [comment]
@cristian-e - please handle this after Modula re-design is finished.
